// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApisApp.Data;

#nullable disable

namespace WebApisApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApisApp.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActionDate")
                        .HasDatabaseName("IX_AuditLogs_ActionDate");

                    b.HasIndex("UserId", "ActionDate")
                        .HasDatabaseName("IX_AuditLogs_UserId_ActionDate");

                    b.HasIndex("TableName", "RecordId", "ActionDate")
                        .HasDatabaseName("IX_AuditLogs_TableName_RecordId_ActionDate");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.BlacklistedToken", b =>
                {
                    b.Property<Guid>("BlacklistedTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BlacklistedTokenId");

                    b.ToTable("BlacklistedTokens");
                });

            modelBuilder.Entity("WebApisApp.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Devices_DeviceCode");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("IX_Devices_LocationId");

                    b.HasIndex("IsActive", "LastSeenAt")
                        .HasDatabaseName("IX_Devices_IsActive_LastSeenAt");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Locations_LocationCode");

                    b.HasIndex("LocationName")
                        .HasDatabaseName("IX_Locations_LocationName");

                    b.HasIndex("LocationType", "IsActive")
                        .HasDatabaseName("IX_Locations_LocationType_IsActive");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.PasswordResetOtp", b =>
                {
                    b.Property<Guid>("PasswordResetOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PasswordResetOtpId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_PasswordResetOtps_ExpiresAt");

                    b.HasIndex("UserId", "IsUsed", "ExpiresAt")
                        .HasDatabaseName("IX_PasswordResetOtps_UserId_IsUsed_ExpiresAt");

                    b.ToTable("PasswordResetOtps", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GlobalAverageCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_ProductCode");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_Products_ProductName");

                    b.HasIndex("ProductType", "IsActive")
                        .HasDatabaseName("IX_Products_ProductType_IsActive");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.ProductionOperation", b =>
                {
                    b.Property<Guid>("ProductionOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManufacturedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("QuantityProduced")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductionOperationId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LocationId", "ProductionDate")
                        .HasDatabaseName("IX_ProductionOperations_LocationId_ProductionDate");

                    b.HasIndex("ManufacturedProductId", "ProductionDate")
                        .HasDatabaseName("IX_ProductionOperations_ManufacturedProductId_ProductionDate");

                    b.ToTable("ProductionOperations", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.ProductionOperationItem", b =>
                {
                    b.Property<Guid>("ProductionOperationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductionOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityConsumed")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("RawProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductionOperationItemId");

                    b.HasIndex("ProductionOperationId")
                        .HasDatabaseName("IX_ProductionOperationItems_ProductionOperationId");

                    b.HasIndex("RawProductId")
                        .HasDatabaseName("IX_ProductionOperationItems_RawProductId");

                    b.HasIndex("ProductionOperationId", "RawProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductionOperationItems_ProductionOperationId_RawProductId");

                    b.ToTable("ProductionOperationItems", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.ProductRecipe", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ManufacturedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityNeeded")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("RawProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId");

                    b.HasIndex("RawProductId")
                        .HasDatabaseName("IX_ProductRecipes_RawProductId");

                    b.HasIndex("ManufacturedProductId", "RawProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProductRecipes_ManufacturedProductId_RawProductId");

                    b.ToTable("ProductRecipes", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("PurchaseInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseInvoiceId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InvoiceNumber")
                        .HasDatabaseName("IX_PurchaseInvoices_InvoiceNumber");

                    b.HasIndex("LocationId", "InvoiceDate")
                        .HasDatabaseName("IX_PurchaseInvoices_LocationId_InvoiceDate");

                    b.HasIndex("Status", "InvoiceDate")
                        .HasDatabaseName("IX_PurchaseInvoices_Status_InvoiceDate");

                    b.HasIndex("SupplierId", "InvoiceDate")
                        .HasDatabaseName("IX_PurchaseInvoices_SupplierId_InvoiceDate");

                    b.ToTable("PurchaseInvoices", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.PurchaseInvoiceItem", b =>
                {
                    b.Property<Guid>("PurchaseInvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseInvoiceItemId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_PurchaseInvoiceItems_ProductId");

                    b.HasIndex("PurchaseInvoiceId")
                        .HasDatabaseName("IX_PurchaseInvoiceItems_PurchaseInvoiceId");

                    b.HasIndex("PurchaseInvoiceId", "ProductId")
                        .HasDatabaseName("IX_PurchaseInvoiceItems_PurchaseInvoiceId_ProductId");

                    b.ToTable("PurchaseInvoiceItems", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId", "DeviceId")
                        .HasDatabaseName("IX_RefreshTokens_UserId_DeviceId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.ServerChangeLog", b =>
                {
                    b.Property<long>("ChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChangeId"), 1L, 1);

                    b.Property<long>("ChangeVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChangeId");

                    b.HasIndex("ChangeVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_ServerChangeLog_ChangeVersion");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("IX_ServerChangeLog_ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LocationId", "ChangeVersion")
                        .HasDatabaseName("IX_ServerChangeLog_LocationId_ChangeVersion");

                    b.HasIndex("EntityName", "EntityId", "ChangeVersion")
                        .HasDatabaseName("IX_ServerChangeLog_EntityName_EntityId_ChangeVersion");

                    b.ToTable("ServerChangeLog", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.StockBalance", b =>
                {
                    b.Property<Guid>("StockBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMovementAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StockBalanceId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_StockBalances_ProductId");

                    b.HasIndex("LocationId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_StockBalances_LocationId_ProductId");

                    b.ToTable("StockBalances", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.StockCount", b =>
                {
                    b.Property<Guid>("StockCountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CountDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StockCountId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LocationId", "CountDate")
                        .HasDatabaseName("IX_StockCounts_LocationId_CountDate");

                    b.HasIndex("Status", "CountDate")
                        .HasDatabaseName("IX_StockCounts_Status_CountDate");

                    b.ToTable("StockCounts", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.StockCountItem", b =>
                {
                    b.Property<Guid>("StockCountItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DifferenceQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StockCountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SystemQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StockCountItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockCountId")
                        .HasDatabaseName("IX_StockCountItems_StockCountId");

                    b.HasIndex("StockCountId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_StockCountItems_StockCountId_ProductId");

                    b.ToTable("StockCountItems", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.StockMovement", b =>
                {
                    b.Property<Guid>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityIn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QuantityOut")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StockMovementId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProductId", "MovementDate")
                        .HasDatabaseName("IX_StockMovements_ProductId_MovementDate");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("IX_StockMovements_ReferenceType_ReferenceId");

                    b.HasIndex("LocationId", "ProductId", "MovementDate")
                        .HasDatabaseName("IX_StockMovements_LocationId_ProductId_MovementDate");

                    b.ToTable("StockMovements", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SupplierId");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Suppliers_Phone");

                    b.HasIndex("SupplierName")
                        .HasDatabaseName("IX_Suppliers_SupplierName");

                    b.HasIndex("IsActive", "SupplierName")
                        .HasDatabaseName("IX_Suppliers_IsActive_SupplierName");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.SupplierPayment", b =>
                {
                    b.Property<Guid>("SupplierPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PurchaseInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SystemPaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SupplierPaymentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PurchaseInvoiceId")
                        .HasDatabaseName("IX_SupplierPayments_PurchaseInvoiceId");

                    b.HasIndex("SystemPaymentMethodId")
                        .HasDatabaseName("IX_SupplierPayments_SystemPaymentMethodId");

                    b.HasIndex("SupplierId", "PaymentDate")
                        .HasDatabaseName("IX_SupplierPayments_SupplierId_PaymentDate");

                    b.ToTable("SupplierPayments", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.SystemPaymentMethod", b =>
                {
                    b.Property<Guid>("SystemPaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MethodType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SystemPaymentMethodId");

                    b.HasIndex("MethodType", "IsActive")
                        .HasDatabaseName("IX_SystemPaymentMethods_MethodType_IsActive");

                    b.ToTable("SystemPaymentMethods", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.TransferRequest", b =>
                {
                    b.Property<Guid>("TransferRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PreparedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransferCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TransferRequestId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("TransferCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_TransferRequests_TransferCode");

                    b.HasIndex("Status", "RequestDate")
                        .HasDatabaseName("IX_TransferRequests_Status_RequestDate");

                    b.HasIndex("FromLocationId", "Status", "RequestDate")
                        .HasDatabaseName("IX_TransferRequests_FromLocationId_Status_RequestDate");

                    b.HasIndex("ToLocationId", "Status", "RequestDate")
                        .HasDatabaseName("IX_TransferRequests_ToLocationId_Status_RequestDate");

                    b.ToTable("TransferRequests", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.TransferRequestItem", b =>
                {
                    b.Property<Guid>("TransferRequestItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ApprovedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ReceivedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RequestedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ShippedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("TransferRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TransferRequestItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransferRequestId")
                        .HasDatabaseName("IX_TransferRequestItems_TransferRequestId");

                    b.HasIndex("TransferRequestId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TransferRequestItems_TransferRequestId_ProductId");

                    b.ToTable("TransferRequestItems", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("IX_Users_LocationId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_UserName");

                    b.HasIndex("UserType", "IsActive")
                        .HasDatabaseName("IX_Users_UserType_IsActive");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WebApisApp.Models.AuditLog", b =>
                {
                    b.HasOne("WebApisApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApisApp.Models.Device", b =>
                {
                    b.HasOne("WebApisApp.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WebApisApp.Models.PasswordResetOtp", b =>
                {
                    b.HasOne("WebApisApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApisApp.Models.ProductionOperation", b =>
                {
                    b.HasOne("WebApisApp.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Location", "Location")
                        .WithMany("ProductionOperations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Product", "ManufacturedProduct")
                        .WithMany("ProductionOperations")
                        .HasForeignKey("ManufacturedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Location");

                    b.Navigation("ManufacturedProduct");
                });

            modelBuilder.Entity("WebApisApp.Models.ProductionOperationItem", b =>
                {
                    b.HasOne("WebApisApp.Models.ProductionOperation", "ProductionOperation")
                        .WithMany("Items")
                        .HasForeignKey("ProductionOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Product", "RawProduct")
                        .WithMany("ProductionOperationItems")
                        .HasForeignKey("RawProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOperation");

                    b.Navigation("RawProduct");
                });

            modelBuilder.Entity("WebApisApp.Models.ProductRecipe", b =>
                {
                    b.HasOne("WebApisApp.Models.Product", "ManufacturedProduct")
                        .WithMany("RecipesAsManufactured")
                        .HasForeignKey("ManufacturedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Product", "RawProduct")
                        .WithMany("RecipesAsRaw")
                        .HasForeignKey("RawProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManufacturedProduct");

                    b.Navigation("RawProduct");
                });

            modelBuilder.Entity("WebApisApp.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("WebApisApp.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Location", "Location")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Supplier", "Supplier")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Location");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebApisApp.Models.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("WebApisApp.Models.Product", "Product")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("WebApisApp.Models.RefreshToken", b =>
                {
                    b.HasOne("WebApisApp.Models.Device", "Device")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApisApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApisApp.Models.ServerChangeLog", b =>
                {
                    b.HasOne("WebApisApp.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApisApp.Models.Device", "Device")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApisApp.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangedByUser");

                    b.Navigation("Device");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WebApisApp.Models.StockBalance", b =>
                {
                    b.HasOne("WebApisApp.Models.Location", "Location")
                        .WithMany("StockBalances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApisApp.Models.StockCount", b =>
                {
                    b.HasOne("WebApisApp.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Location", "Location")
                        .WithMany("StockCounts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WebApisApp.Models.StockCountItem", b =>
                {
                    b.HasOne("WebApisApp.Models.Product", "Product")
                        .WithMany("StockCountItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.StockCount", "StockCount")
                        .WithMany("Items")
                        .HasForeignKey("StockCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockCount");
                });

            modelBuilder.Entity("WebApisApp.Models.StockMovement", b =>
                {
                    b.HasOne("WebApisApp.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Location", "Location")
                        .WithMany("StockMovements")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApisApp.Models.SupplierPayment", b =>
                {
                    b.HasOne("WebApisApp.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Payments")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApisApp.Models.Supplier", "Supplier")
                        .WithMany("Payments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.SystemPaymentMethod", "SystemPaymentMethod")
                        .WithMany("SupplierPayments")
                        .HasForeignKey("SystemPaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("Supplier");

                    b.Navigation("SystemPaymentMethod");
                });

            modelBuilder.Entity("WebApisApp.Models.TransferRequest", b =>
                {
                    b.HasOne("WebApisApp.Models.Location", "FromLocation")
                        .WithMany("FromTransferRequests")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.Location", "ToLocation")
                        .WithMany("ToTransferRequests")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromLocation");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("WebApisApp.Models.TransferRequestItem", b =>
                {
                    b.HasOne("WebApisApp.Models.Product", "Product")
                        .WithMany("TransferRequestItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApisApp.Models.TransferRequest", "TransferRequest")
                        .WithMany("Items")
                        .HasForeignKey("TransferRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("TransferRequest");
                });

            modelBuilder.Entity("WebApisApp.Models.User", b =>
                {
                    b.HasOne("WebApisApp.Models.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WebApisApp.Models.Device", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("WebApisApp.Models.Location", b =>
                {
                    b.Navigation("FromTransferRequests");

                    b.Navigation("ProductionOperations");

                    b.Navigation("PurchaseInvoices");

                    b.Navigation("StockBalances");

                    b.Navigation("StockCounts");

                    b.Navigation("StockMovements");

                    b.Navigation("ToTransferRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApisApp.Models.Product", b =>
                {
                    b.Navigation("ProductionOperationItems");

                    b.Navigation("ProductionOperations");

                    b.Navigation("PurchaseInvoiceItems");

                    b.Navigation("RecipesAsManufactured");

                    b.Navigation("RecipesAsRaw");

                    b.Navigation("StockBalances");

                    b.Navigation("StockCountItems");

                    b.Navigation("StockMovements");

                    b.Navigation("TransferRequestItems");
                });

            modelBuilder.Entity("WebApisApp.Models.ProductionOperation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WebApisApp.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebApisApp.Models.StockCount", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WebApisApp.Models.Supplier", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PurchaseInvoices");
                });

            modelBuilder.Entity("WebApisApp.Models.SystemPaymentMethod", b =>
                {
                    b.Navigation("SupplierPayments");
                });

            modelBuilder.Entity("WebApisApp.Models.TransferRequest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
